{% set name = "tune-sklearn" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # NOTE: pypi doesnt contain a source package for it. See
  # https://github.com/ray-project/tune-sklearn/issues/159
  url: https://github.com/ray-project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f6d531f99a02de4a420cbefb96de64c8db4a014f2c7352f38a6a7a37e2103614
  patches:
    # Remove this patch for ray-core/ray-tune >=2.6.0, because it's will be deprecated and removed from the source code
    # see https://github.com/ray-project/ray/blob/3aa6ede43743a098b5e0eb37ec11505f46100313/python/ray/tune/integration/mlflow.py#L15-L20
    - fix_ray_tune_import.patch

build:
  number: 1
  # ray-core/ray-tune 2.3.0 haven't Python 3.11 support at the moment.
  skip: True  # [py<38 or py>310 or s390x or ppc64le]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.16
    - ray-tune >=2.0.0
    - scipy
    - scikit-learn
    # utils.py requires packaging indirectly from ray-air,
    # see https://github.com/ray-project/tune-sklearn/blob/v0.4.6/tune_sklearn/utils.py#L17C1-L17C61 and
    # https://github.com/ray-project/ray/blame/ray-2.3.0/python/ray/tune/integration/mlflow.py#L9
    - packaging

test:
  imports:
    - tune_sklearn
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ray-project/tune-sklearn
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A drop-in replacement for Scikit-Learn's GridSearchCV / RandomizedSearchCV -- but with cutting edge hyperparameter tuning techniques.
  description: |
    A drop-in replacement for Scikit-Learn's GridSearchCV / RandomizedSearchCV -- but with cutting edge hyperparameter tuning techniques.
  doc_url: https://github.com/ray-project/tune-sklearn/blob/master/README.md
  dev_url: https://github.com/ray-project/tune-sklearn
